### ISSUE TITLE
Some guidance on refresh flow 

### ISSUE THREAD

**Issue by totegsito** [brocoders/nestjs-boilerplate#1079]
In first place, thanks so much for the huge effort on this boilerplate. It is one of the most complete one I have used.

I have been reading the code for the new refresh session workflow and did a couple of tests using the swagger documentation but I have been unable make it work. 

It would be much appreciated to have some guidance about which parameters it should receive.

Thanks in advance

**Comment by Shchepotin** [comment]
@totegsito thanks for your feedback!

I'm working on it 😉

**Comment by Shchepotin** [comment]
@totegsito done 🥳
