### ISSUE TITLE
The server is not turning on

### ISSUE THREAD

**Issue by Akezh** [brocoders/nestjs-boilerplate#1113]
**Describe the bug**
After cloning, the server (api :3000) is not turning on

**To Reproduce**
1. Follow "Quick Run Steps"
2. Api (localhost:3000) container has the following error:

**Screenshots**
<img width="800" alt="Screenshot 2023-08-22 at 11 03 22" src="https://github.com/brocoders/nestjs-boilerplate/assets/39896828/37afe0bf-41fb-4805-9339-2ce497fc53c9">

**Desktop (please complete the following information):**
 - OS: Mac Venture 13.5
 - NodeJS Version 18.16.0
 - Docker version 23.0.4
 - Docker Compose version 2.17.2

**Terminal logs**
```wait-for-it.sh: waiting 15 seconds for postgres:5432
wait-for-it.sh: postgres:5432 is available after 1 seconds
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
}
wait-for-it.sh: waiting 15 seconds for postgres:5432
wait-for-it.sh: postgres:5432 is available after 0 seconds
> passporting@0.0.1 migration:run
> npm run typeorm -- --dataSource=src/database/data-source.ts migration:run
> passporting@0.0.1 typeorm```

**Comment by Akezh** [comment]
Thank you! I have figured it out:
1. Installed postgres locally
2. Created user
3. Created database
4. Pointed them on .env file and it worked

**Comment by fac3m4n** [comment]
@Shchepotin I still have that error on docker. Just running the quick start

**Comment by fac3m4n** [comment]
> @Shchepotin I still have that error on docker. Just running the quick start

nvm all good. messed the env file

**Comment by mohrazzak** [comment]
> Thank you! I have figured it out:
> 
> 1. Installed postgres locally
> 2. Created user
> 3. Created database
> 4. Pointed them on .env file and it worked

That didn't work for me is there any thing else you did ?
