### ISSUE TITLE
SyntaxError: Unexpected token 'for'

### ISSUE THREAD

**Issue by nmashchenko** [brocoders/nestjs-boilerplate#1165]
**Describe the bug**
Moving all files to folder server breaks e2e docker tests

**To Reproduce**
1. Move all files to server folder
2. Add working-directory: ./server under - name: Run e2e tests
4. Wait until CI runs

**Expected behavior**
CI passes tests

**Screenshots**
![image](https://github.com/brocoders/nestjs-boilerplate/assets/52038455/6285dd2a-8e84-41e2-880e-1ec1d6e4da51)

**Desktop (please complete the following information):**
 N/A: GitHub actions

**Additional context**
Tested in local repo, might missing something in docker setup:
https://github.com/nmashchenko/nestjs

**Comment by Shchepotin** [comment]
@nmashchenko your `wait-for-it.sh` doesn't have `executable` permission. You can change it via `chmod`

Actual result:
<img width="548" alt="Screenshot 2023-09-24 at 17 03 48" src="https://github.com/brocoders/nestjs-boilerplate/assets/6001723/ab4e91bc-18d2-4111-bb97-67ebb7ab6032">

Expected result:
<img width="549" alt="Screenshot 2023-09-24 at 17 04 45" src="https://github.com/brocoders/nestjs-boilerplate/assets/6001723/aebc7193-b065-4913-b7f5-2911f9e20642">

**Comment by Shchepotin** [comment]
@nmashchenko see patch here https://github.com/brocoders/nestjs-boilerplate/pull/1167/files

**Comment by nmashchenko** [comment]
@Shchepotin works perfectly now! Thanks!
![image](https://github.com/brocoders/nestjs-boilerplate/assets/52038455/16c39584-9b5f-4137-9094-6a01535a4feb)
