### ISSUE TITLE
Deploying to render.com

### ISSUE THREAD

**Issue by kibolho** [brocoders/nestjs-boilerplate#1216]
**Describe the bug**
First of all, thanks for the amazing repo! 
I am trying to deploy it using docker inside [render](https://render.com)

**To Reproduce**
1. Go to render.com
2. Create a new web service
3. Use a free instance
4. Use the default configuration
5. Deploy it

**Expected behavior**
Deploy successfully

**Screenshots**
![Screenshot 2023-10-25 at 16 38 17](https://github.com/brocoders/nestjs-boilerplate/assets/1197923/f9db4749-6d77-4138-8949-9b318a4bb70a)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - NodeJS Version [e.g. 18.16.0]

**Additional context**

**Comment by kibolho** [comment]
Seems like Render.com doesn't support disk for normal docker deployment

**Comment by mohrazzak** [comment]
> Seems like Render.com doesn't support disk for normal docker deployment

@kibolho Did you solve it by any chance ?
