### ISSUE TITLE
can not connect with mongoose DB

### ISSUE THREAD

**Issue by techstarMahesh** [brocoders/nestjs-boilerplate#1287]
**Describe the bug**
I try to use mongodb but not able to use i change in env file and then install mongodb npm module and try to create use and then login it is not work

**To Reproduce**
1. Change env for mongodb
2. Install `npm i mongodb`
4. Create user. 
5. Login user
6. You can see the use login error. 

**Expected behavior**
I want to do all task that i do in postgresql

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - NodeJS Version [18.16.0]

**Comment by Shchepotin** [comment]
@techstarMahesh  We are working on switching between Mongoose and TypeORM. The release will be very soon!
