### ISSUE TITLE
Run seeds gives error

### ISSUE THREAD

**Issue by iam-dev** [brocoders/nestjs-boilerplate#1334]
**Describe the bug**
 const salt = await bcrypt.genSalt();
                                ^
TypeError: Cannot read properties of undefined (reading 'genSalt')
    at UserSeedService.run (/xx/nestjs/src/database/seeds/relational/user/user-seed.service.ts:26:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runSeed (/xx/nestjs/src/database/seeds/relational/run-seed.ts:13:3)

**To Reproduce**
1. Go to folder, and copy `env-example-relational` as `.env`.

   ```bash
   cd my-app/
   cp env-example-relational .env
   ```

1. Change `DATABASE_HOST=postgres` to `DATABASE_HOST=localhost`

   Change `MAIL_HOST=maildev` to `MAIL_HOST=localhost`

1. Run additional container:

   ```bash
   docker compose up -d postgres adminer maildev
   ```

1. Install dependency

   ```bash
   npm install
   ```

1. Run migrations

   ```bash
   npm run migration:run
   ```

1. Run seeds

   ```bash
   npm run seed:run:relational
   ```

Error occurred

**Expected behavior**
No error when running npm run seed:run:relational

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Mac Os X, 14.0 (23A344), Apple M2]
 - NodeJS Version v20.11.0
 - 

**Additional context**
N.a

**Comment by Shameel123** [comment]
@Shchepotin May I try and fix this?

**Comment by Shchepotin** [comment]
@Shameel123 If you are faced with the same problem and have a solution you can try to do this

**Comment by Shameel123** [comment]
@Shchepotin Did not get any error related to this issue.
Noticed some deprecated libraries, will create a separate issue for that.
