### ISSUE TITLE
Error Generating Migration: TypeError Reading 'COLLATION' Property

### ISSUE THREAD

**Issue by itsChathurangaJ** [brocoders/nestjs-boilerplate#1432]
**Describe the bug**
When attempting to generate a new migration , I encounter a TypeError related to reading the 'COLLATION' property. This error occurs during the schema reflection process, preventing the migration file from being generated.

**To Reproduce**
1. Modify entity definitions to correct relationships between entities.
2. Run migration generation command: npm run migration:generate -- src/database/migrations/db-changes
3. Encounter the error during the migration generation process.

Initially, my entities had the following relationship definitions:

```
// Incorrect version
@ManyToOne(() => Course, (course) => course.intakes)
course: Course;

@ManyToOne(() => Lecturer, (lecturer) => lecturer.intakes)
lecturer: Lecturer;

```

I corrected the relationships to properly map to `scrapedReviews`:

```
// correct version
@ManyToOne(() => Course, (course) => course.scrapedReviews)
course: Course;

@ManyToOne(() => Lecturer, (lecturer) => lecturer.scrapedReviews)
lecturer: Lecturer;
```

After making this change, I attempted to generate a new migration to reflect these updates by running migration command. and it fails and gives an error 

**Expected behavior**
The migration generation process should complete successfully, reflecting the recent changes made to the entity definitions in the generated migration file.

**Actual behavior**
The process fails with the following error message:
`Error during migration generation:
TypeError: Cannot read properties of undefined (reading 'COLLATION')
    at /path/to/project/node_modules/typeorm/src/driver/mysql/MysqlQueryRunner.ts:2571:53
    ...
`

**Desktop (please complete the following information):**
 - OS : Mac OS - Sonoma 14.3
 - NodeJS Version 18.16.0

**Additional context**
- This issue arose after correcting the inverse side of relationships in my entity definitions.
- I have verified that my MySQL version is compatible with the current TypeORM version I'm using.
- I have attempted to update TypeORM to the latest version and checked my database schema for any unusual configurations related to collations, with no success in resolving the issue.

**Comment by Shchepotin** [comment]
@itsChathurangaJ It looks like a TypeORM issue, please try to find a similar issue or create a new one https://github.com/typeorm/typeorm/issues
