### ISSUE TITLE
User doesn't have a role property upon token refresh. Leads to false 403's

### ISSUE THREAD

**Issue by JordanTreDaniel** [brocoders/nestjs-boilerplate#1442]
**Describe the bug**
Upon refreshing the auth token, the "user" object attached to the "request" is missing the "role" property. When using the "RolesGuard", the user must have the "role" property present in order to pass; it does not. This leads to the RolesGuard rejecting with a 403

**To Reproduce**
1. Set the token expiration to a small number.
2. Trigger the login, log the "request.user" from `RolesGuard`, observe that is has a "role" property upon the initial login.
3. Trigger the refresh.
4. Test the same route as in step 2. The user doesn't have a role property anymore.

**Expected behavior**
I would expect request.user to have consistent properties, and for the route's specifying roles.user to not reject the user on a 403.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - NodeJS Version `20.9.0`

**Additional context**
none.

**Comment by JordanTreDaniel** [comment]
Side note: Thank you so much for making this and putting it out. I would fix the problem, but I myself am learning more about  Nest from the examples laid forth in this project.

**Comment by Shchepotin** [comment]
@JordanTreDaniel thank you! Fixed.
