### ISSUE TITLE
Husky failed to run 'npm run test'

### ISSUE THREAD

**Issue by hankaibo** [brocoders/nestjs-boilerplate#1498]
**Describe the bug**
Running npm run test fails when committing code.

**To Reproduce**
1. ...
2. npm run app:config
    Note: choose relational database, choose relational database, choose relational.
3. git commit 
    No tests found, exiting with code 1.
    Run with '--passWithNoTests' to exit with code 0.

    Becase the file 'domain-to-document-condition.spec.ts' has been deleted.

**Expected behavior**
When I commit the code, `npm run test` runs successfully.

**Screenshots**
![image](https://github.com/brocoders/nestjs-boilerplate/assets/5361465/c0041aca-444b-4e8a-ac61-8d1732e2c5ad)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - NodeJS Version 20.12.2
 - Database Postgis

**Comment by Shchepotin** [comment]
@hankaibo  Fixed. Thank you!
