### ISSUE TITLE
Why is many to 1?

### ISSUE THREAD

**Issue by hankaibo** [brocoders/nestjs-boilerplate#1528]
Hi.
I have a question, when defining the 'photo' at line [L93](https://github.com/brocoders/nestjs-boilerplate/blob/main/src/users/infrastructure/persistence/relational/entities/user.entity.ts#L93), why use 'ManyToOne' instead of 'OneToOne' or other?

**Comment by Shchepotin** [comment]
@hankaibo this was a mistake. Fixed

**Comment by Shchepotin** [comment]
@hankaibo good catch! Please remove manually these https://github.com/brocoders/nestjs-boilerplate/blob/main/.github/workflows/docker-e2e.yml#L16-L22 or https://github.com/brocoders/nestjs-boilerplate/blob/main/.github/workflows/docker-e2e.yml#L24-L30 lines. A little bit later I'll move it to "install scripts"
