### ISSUE TITLE
File upload response returns entire URL in path field

### ISSUE THREAD

**Issue by Joelfrewy** [brocoders/nestjs-boilerplate#1533]
**Describe the bug**
The file upload response returns the entire URL in path field
```
{
  "file": {
    "id": "663a2552b5b5174fc7233c04",
    "path": "http://localhost:3000/api/v1/files/a18dc102653eac2715f5d.jpg"
  }
}
```
This is misaligned with the `/api/v1/files/{path}` endpoint which expects only the file name

**To Reproduce**
1. Use the `/api/v1/files/upload` endpoint to upload a file
2. See path field in response object

**Expected behavior**
The `path` field should be updated to display only the file name, or the field should be renamed to `link`

**Screenshots**
<img width="578" alt="Screenshot 2024-05-07 at 11 05 33 PM" src="https://github.com/brocoders/nestjs-boilerplate/assets/8296132/509590f2-373e-4871-97e2-f45c28384e18">

**Comment by Shchepotin** [comment]
@Joelfrewy `/api/v1/files/{path}` is used only for showing local files. It had been removed from Swagger to avoid confusion #1537.
