### ISSUE TITLE
Feature Request: Upgrade ESLint from 8.x to 9.x

### ISSUE THREAD

**Issue by sAtluna** [brocoders/nestjs-boilerplate#1563]
**Describe the bug**
More a feature request. Would it be possible to upgrade the ESLint dependency from 8.x to 9.x?

Thanks for this great boilerplate!

**Comment by Shchepotin** [comment]
@sAtluna stable version (v7) of `@typescript-eslint/eslint-plugin` and `@typescript-eslint/parser doesn't support eslint v9. We must wait until the stable version of `@typescript-eslint` will upgrade from v7 to v8.

Details: https://github.com/typescript-eslint/typescript-eslint/issues/8211

**Comment by sAtluna** [comment]
Thanks @Shchepotin. I see. Should I close the ticket?

**Comment by Shchepotin** [comment]
@sAtluna I'll close once this problem is fixed :)

**Comment by abhijeetnarvekar** [comment]
typescript-eslint v8 supporting ESLint v9 is now released https://typescript-eslint.io/blog/announcing-typescript-eslint-v8/
