### ISSUE TITLE
Error: Unable to open file: "/app/src/database/data-source.ts". when publishing vie herouku

### ISSUE THREAD

**Issue by SaqoTadevosyan** [brocoders/nestjs-boilerplate#1588]
I receive this error when trying to build with herouku
`
> nestjs-boilerplate@0.0.1 migration:run
> npm run typeorm -- --dataSource=src/database/data-source.ts migration:run
> nestjs-boilerplate@0.0.1 typeorm
> env-cmd ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js --dataSource=src/database/data-source.ts migration:run
Error during migration run:
Error: Unable to open file: "/app/src/database/data-source.ts". Wrong driver: "undefined" given. Supported drivers are: "aurora-mysql", "aurora-postgres", "better-sqlite3", "capacitor", "cockroachdb", "cordova", "expo", "mariadb", "mongodb", "mssql", "mysql", "nativescript", "oracle", "postgres", "react-native", "sap", "sqlite", "sqljs", "spanner".
    at Function.loadDataSource (/app/node_modules/src/commands/CommandUtils.ts:22:19)
    at async Object.handler (/app/node_modules/src/commands/MigrationRunCommand.ts:42:26)
npm notice
npm notice New minor version of npm available! 10.7.0 -> 10.8.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.1
npm notice To update run: npm install -g npm@10.8.1
npm notice`

**Comment by Shchepotin** [comment]
@SaqoTadevosyan did you set ENV variables in Heroku?

**Comment by SaqoTadevosyan** [comment]
> @SaqoTadevosyan did you set ENV variables in Heroku?

No(
thank you
