### ISSUE TITLE
TSError: Unable to compile TypeScript (running "npm run seed:run:relational")

### ISSUE THREAD

**Issue by IFeofilov** [brocoders/nestjs-boilerplate#1610]
**Describe the bug**
I tried to create a new project following the instructions - [Comfortable development (PostgreSQL + TypeORM)](https://github.com/brocoders/nestjs-boilerplate/blob/main/docs/installing-and-running.md). At step 8 (Run seeds) an error occurs: 
```
src/database/seeds/relational/seed.module.ts:25:7 - error TS2322: Type '(options: DataSourceOptions) => Promise<DataSource>' is not assignable to type 'TypeOrmDataSourceFactory'.
  Types of parameters 'options' and 'options' are incompatible.
    Type 'DataSourceOptions | undefined' is not assignable to type 'DataSourceOptions'.
      Type 'undefined' is not assignable to type 'DataSourceOptions'.
```

**To Reproduce**
1. Just follow the instructions steps.

**Expected behavior**
The seeds are applied to the database successfully.

**Screenshots**
<img width="1281" alt="image" src="https://github.com/brocoders/nestjs-boilerplate/assets/172439869/d7543122-2069-4728-b27f-22a5fce3c4ef">

**Desktop (please complete the following information):**
 - OS: MacOS
 - NodeJS Version: v22.3.0
 - Database: PostgreSQL

**Comment by Shchepotin** [comment]
@IFeofilov which package manager are you using?

**Comment by IFeofilov** [comment]
@Shchepotin I tried both package managers and yarn and npm
