### ISSUE TITLE
Failed to update user

### ISSUE THREAD

**Issue by hankaibo** [brocoders/nestjs-boilerplate#1630]
**Describe the bug**
When I try to update the user profile, it tells me "{"status":422,"errors":{"email":"emailAlreadyExists"}}".

**Additional context**
I found that the variable `id` is a string on https://github.com/brocoders/nestjs-boilerplate/blob/main/src/users/users.controller.ts#L123

But the id of user in the database is a numebr, and used strict equality ('===') for the comparison on https://github.com/brocoders/nestjs-boilerplate/blob/main/src/users/users.service.ts#L153

This is the root of the problem.

**Comment by ovibutt** [comment]
@hankaibo are you sending email also in the payload? I removed the email from the payload and it worked for me.

Which I guess is the right case. Normally users are not allowed to update their emails.

**Comment by Shchepotin** [comment]
@hankaibo please, do not send the "email" field if you do not update the value.
