### ISSUE TITLE
Api's running on docker are not able to connect pg running on docker.

### ISSUE THREAD

**Issue by ovibutt** [brocoders/nestjs-boilerplate#1637]
**Describe the bug**
I ran my backend and all other images on dockers but when I try to execute all of my containers are running properly but the api container shuts down and gives me this error.

**To Reproduce**
1. run docker commands in vs code.
2. See all containers running in vs code.
3. see logs of backend-api-1

**Expected behavior**
I want the application to run properly and should be able to open it on 3000 port.

**Screenshots**
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/6e1cd9de-0b2b-4264-869c-b381272ebf35">

**Desktop (please complete the following information):**
 - OS: MacOS 14.5 (Sanoma) M3 chip
 - NodeJS Version: 20
 - Database: Postgres

**Additional context**

**Comment by Shchepotin** [comment]
@ovibutt you need to use the container's name (not localhost or 127.0.0.1) for connection under docker.

Try to set `DATABASE_HOST=postgres` in `.env` and check again.

**Comment by ovibutt** [comment]
<img width="1474" alt="image" src="https://github.com/user-attachments/assets/1b2f0e5c-be4a-495f-9ac2-1584ee398e57">

I have tried all DATABASE_HOST=postgres, DATABASE_HOST=postgres-1, DATABASE_HOST=hypd-backend-postgres-1

none of them is working.

**Comment by ovibutt** [comment]
it worked thanks 👍
