### ISSUE TITLE
Bug - Add field in entity

### ISSUE THREAD

**Issue by mithang** [brocoders/nestjs-boilerplate#1680]
**To Reproduce**
1. npm run generate:resource:relational -- --name=products

2. npm run migration:generate -- src/database/migrations/CreateProductTable

3. npm run migration:run

4. Add "name" field in products.entity.ts

5. npm run migration:generate -- src/database/migrations/AddNameFieldTable
=> No changes in database schema were found - cannot generate a migration. To create a new empty migration use "typeorm migration:create" command

How to fix? Please

**Comment by Shchepotin** [comment]
@mithang how did you add the field?

**Comment by mithang** [comment]
> @mithang how did you add the field?

this is my fault. i forget added @Column() in field
