### ISSUE TITLE
How to select specific columns in a database query?

### ISSUE THREAD

**Issue by sinhpn92** [brocoders/nestjs-boilerplate#1723]
Hello,
Selecting specific fields when querying the database is crucial for improving performance and reducing unnecessary load on the database. I am trying to figure out how I should apply this with your current design when I want to select specific necessary fields. Does anyone have any suggestions for this? I haven't found the answer yet. Should we create a separate function for this in the Repository?

Thank you for taking the time to answer my question.

**Comment by Shchepotin** [comment]
> Should we create a separate function for this in the Repository?

This is correct way 👍
