### ISSUE TITLE
add user field to file

### ISSUE THREAD

**Issue by isaachamid** [brocoders/nestjs-boilerplate#1730]
Hi there,
thanks for your great job,

how can i define user (created by) field to Products table in mongo?

Regards

**Comment by Shchepotin** [comment]
Hello @isaachamid 

There are a couple of strategies for storage: duplication data (for good performance) and reference. Currently boilerplate has one example for a photo (duplication) https://github.com/brocoders/nestjs-boilerplate/blob/2cb1883d5a5c33125ae98d02bdbe9d050b808506/src/users/infrastructure/persistence/document/entities/user.schema.ts#L82-L89

But the same will be for references.

Also, we are working on CLI which will help create fields like this in a few seconds.
