### ISSUE TITLE
authentication flow

### ISSUE THREAD

**Issue by axelverglas** [brocoders/nestjs-boilerplate#1731]
hello,

Is it possible to make multi-app authentication, meaning that the tokens are updated on several apps at the same time?

Have a nice day

**Comment by Shchepotin** [comment]
@axelverglas Nestjs Boilerplate supports authentication for multiple devices. Please, let us know if you are faced with problems in this flow.

**Comment by axelverglas** [comment]
at the same time ? because when an application refreshes the token it is invalidated on the others

**Comment by Shchepotin** [comment]
> at the same time ?
Yes, we create different sessions for devices

**Comment by Shchepotin** [comment]
> because when an application refreshes the token it is invalidated on the others

Did you face this in the NestJS boilerplate?

**Comment by axelverglas** [comment]
ah ok my app must have a problem then because the token expires

**Comment by axelverglas** [comment]
yes so there are not several sessions

Le 1 oct. 2024 à 22:05, Vladyslav Shchepotin ***@***.***> a écrit :

﻿

because when an application refreshes the token it is invalidated on the others

Did you face this in the NestJS boilerplate?

**Comment by Shchepotin** [comment]
Did you generate one pair of access and refresh tokens and set it on different devices?

**Comment by axelverglas** [comment]
yes exactly

**Comment by Shchepotin** [comment]
In this case, try to invoke `/api/v1/auth/email/login` for each device and set unique pair of refresh and access tokens. It will create separate sessions and devices will not affect each other but will be logged in under one user.
