### ISSUE TITLE
What is the password of adminer?

### ISSUE THREAD

**Issue by mohrazzak** [brocoders/nestjs-boilerplate#1742]
**Describe the bug**

**To Reproduce**
2. Send '....'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - NodeJS Version [e.g. 18.16.0]
 - Database [e.g. PostgreSQL]

**Additional context**

**Comment by mohrazzak** [comment]
![image](https://github.com/user-attachments/assets/4c5284ec-cddc-46ae-b9f2-3668a45bfe12)
its not letting me in

**Comment by mohrazzak** [comment]
@Shchepotin

**Comment by Shchepotin** [comment]
@mohrazzak 

Please show the output of the command:

```bash
docker compose ps -a
```

**Comment by mohrazzak** [comment]
![image](https://github.com/user-attachments/assets/70a6a484-8c4a-47fa-a8c1-1278afd70f33)
@Shchepotin

**Comment by mohrazzak** [comment]
Ok, But they work fine in Tableplus
