### ISSUE TITLE
relational resource generate command results in unnamed files

### ISSUE THREAD

**Issue by adminha** [brocoders/nestjs-boilerplate#1755]
**Describe the bug**
when I use `npm run generate:resource:relational -- --name=Team` to generate resource files, it only creates files with unnamed in content and name, instead of Team. I think something is wrong with hygen...

**Comment by Shchepotin** [comment]
@adminha it works for me.

Could you please provide information about your OS and NodeJS version?

<img width="708" alt="image" src="https://github.com/user-attachments/assets/7e071752-fce4-4a57-8a9c-08a7ad56e1bb">
