### ISSUE TITLE
video in the readme section is broken

### ISSUE THREAD

**Issue by ukpagrace** [brocoders/nestjs-boilerplate#1771]
**Describe the bug**
When I get to a particular part of the video it starts again from beginning

**To Reproduce**
1. Go to '1.34' at the video
2. press 'play'

**Expected behavior**
A video to play to the end 

**Desktop (please complete the following information):**
 - browser chrome

**Additional context**

**Comment by Shchepotin** [comment]
@ukpagrace We use a GitHub video player. Try to reload your browser.
