### ISSUE TITLE
"propertyInReference is not defined" error when adding many to one reference property to document 

### ISSUE THREAD

**Issue by hussain18** [brocoders/nestjs-boilerplate#1827]
**Describe the bug**
When attempting to add a property of type reference to the to a document and choosing the relationship type to many to one, I get the _"propertyInReference is not defined"_ error.

**To Reproduce**
Here are the steps to produce shown in the screenshot:
![Screenshot from 2024-12-11 19-57-53](https://github.com/user-attachments/assets/2c584eb7-20fc-42ca-9388-b6f7a89cfcee)

**Expected behavior**
Add a property of reference type to the document

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04
 - NodeJS: Version v22.11.0
 - Database: MongoDB

**Additional context**
As I went through the _[.hygen/index.js] ( i.e. at line no. 129)_ file, I noticed that the propertyInReference is only asked from user (i.e in CLI) when one to many relationship is chosen. As a result, the value is undefined but still checked in _[.hygen/property/add-to-document/infrastructure/persistence/document/entities/schema.ejs.t] (i.e. line no.  12)_ when many to one relationship is chosen. So I think, that this could be causing the error.

**Comment by Shchepotin** [comment]
Good catch!

https://github.com/brocoders/nestjs-boilerplate/pull/1828/commits/6713812a0dd9d72ef2ee140ffaeb36364b64462d please make changes like here to fix the issue.

**Comment by hussain18** [comment]
Thanks a lot
