### ISSUE TITLE
Migration commands not working in docker and how to generate new migration?

### ISSUE THREAD

**Issue by yashflowz** [brocoders/nestjs-boilerplate#610]
<img width="862" alt="Screenshot 2022-03-22 at 6 08 53 PM" src="https://user-images.githubusercontent.com/84369955/159483834-f2f0aeab-b2a4-409f-86e0-9e2aca52a032.png">

- When we run **npm run migration:run** it gives above error.

- How to generate module specific migration? 

- Currently when we run **npm run migration:generate -- CreateNameTable** it will generate all module migration in one file without docker.

**Comment by Shchepotin** [comment]
@yashflowz please make following steps in `.env`:
1. Change `DATABASE_HOST=postgres` to `DATABASE_HOST=localhost`
2. Change `MAIL_HOST=maildev` to `MAIL_HOST=localhost`

https://github.com/brocoders/nestjs-boilerplate#comfortable-development

**Comment by yashflowz** [comment]
@Shchepotin I have also tried that way but it's giving a database connection error in adminer
<img width="1132" alt="Screenshot 2022-03-22 at 6 28 23 PM" src="https://user-images.githubusercontent.com/84369955/159487242-600fb467-d951-4deb-adfd-11d797554cf1.png">

**Comment by ngurahyudi** [comment]
> <img alt="Screenshot 2022-03-22 at 6 08 53 PM" width="862" src="https://user-images.githubusercontent.com/84369955/159483834-f2f0aeab-b2a4-409f-86e0-9e2aca52a032.png">
> 
> * When we run **npm run migration:run** it gives above error.
> * How to generate module specific migration?
> * Currently when we run **npm run migration:generate -- CreateNameTable** it will generate all module migration in one file without docker.

same here, brother.. the API container can not connect to postgress container

**Comment by ngurahyudi** [comment]
> > <img alt="Screenshot 2022-03-22 at 6 08 53 PM" width="862" src="https://user-images.githubusercontent.com/84369955/159483834-f2f0aeab-b2a4-409f-86e0-9e2aca52a032.png">
> > 
> > * When we run **npm run migration:run** it gives above error.
> > * How to generate module specific migration?
> > * Currently when we run **npm run migration:generate -- CreateNameTable** it will generate all module migration in one file without docker.
> 
> same here, brother.. the API container can not connect to postgress container

I think i found the solution, in the DATABASE_HOST env. don't use localhost but use your postgress container name instead
