### ISSUE TITLE
Migrations does not apply entities

### ISSUE THREAD

**Issue by vladimirpetukhov** [brocoders/nestjs-boilerplate#659]
### Steps
I had installed the project with all requirements. After that delete the migrations folder. 
Try to create migration with `npm run migrate:create Init`.
The result is an empty init.ts migration folder.
Add a new module with an entity.
Try to create migration with `npm run migrate:create Init`.
The result again is an empty init.ts migration folder.

**Comment by Shchepotin** [comment]
Please use `npm run migration:generate -- CreateNameTable`
