### ISSUE TITLE
Docker run failed

### ISSUE THREAD

**Issue by vladimirpetukhov** [brocoders/nestjs-boilerplate#661]
After run docker container it is fail 
/usr/bin/env: 'bash\r': No such file or directory

"[37;40mnpm ERR! Missing script: "start:prod

npm ERR! 

npm ERR! Did you mean this?

npm ERR!     npm run start:prod # run the "start:prod" package script

npm ERR! 

npm ERR! To see a list of scripts, run:

npm ERR!   npm run

npm ERR! A complete log of this run can be found in:

npm ERR!     /root/.npm/_logs/2022-07-20T12_20_18_944Z-debug-0.log

**Comment by youngtype** [comment]
Same here

**Comment by Shchepotin** [comment]
@vladimirpetukhov what OS are you using?

**Comment by vladimirpetukhov** [comment]
Windows 10

**Comment by Shchepotin** [comment]
@vladimirpetukhov got it. Thanks!
