### ISSUE TITLE
how do i use it with pm2 

### ISSUE THREAD

**Issue by kevin4dhd** [brocoders/nestjs-boilerplate#760]
I have finished developing my api and now I want it to work with pm2 so that it works 24/7, the problem is that when I restart my server, it does not connect, I do not know if I have to add something to docker compose, I am something new

**Comment by Shchepotin** [comment]
@kevin4dhd Do you run app via `docker-compose up -d`?

**Comment by kevin4dhd** [comment]
yes but, if I want it to use all the cores of my server and work in cluster mode, using -i max in pm2 works, can the same be done in docker? i'm a bit new

**Comment by Shchepotin** [comment]
@kevin4dhd if you want automatically run your NodeJS app after restart server, you can use this guideline https://pm2.keymetrics.io/docs/usage/startup/
