### ISSUE TITLE
Cannot get value.__entity === "User" in serializer.interceptor.ts file

### ISSUE THREAD

**Issue by Ken099** [brocoders/nestjs-boilerplate#779]
Thank you for the great project.I refer to this repository for learning.
The password was not hidden in the response when the user creation was completed.
I investigated the cause and it seems that __entity was not retrieved in the following if minutes.

```
map((data) => {
    return deepMapObject(data, (value) => {
      if (value.__entity === 'User') {
        userResponseSerializer(value as User);
      }
      return value;
    });
}),
```

Also, the following code was working.

```
map((data) => {
    return deepMapObject(data, (value) => {
      if (value.constructor.name === 'User') {
        userResponseSerializer(value as User);
      }
      return value;
    });
}),
```

I apologize if I am wrong.

**Comment by Shchepotin** [comment]
@Ken099 I can't reproduce your problem, please show me your query to DB.
