### ISSUE TITLE
Change serializer to class-transformer Exclude

### ISSUE THREAD

**Issue by keremkurtulus** [brocoders/nestjs-boilerplate#781]
Thank you for creating an excellent boilerplate!

The serializer way looks great but in my opinion, it is not the best practice. I suggest changing it to Exclude decorator importing from `class-transformer`. Thus, we don't have to deep map and iterate all the JSON results with conditions.

I will create a PR and pin this issue. Please consider my solution and share your thoughts. Thanks!

**Comment by Shchepotin** [comment]
👍
