### ISSUE TITLE
Apple sign in env example

### ISSUE THREAD

**Issue by oularrea** [brocoders/nestjs-boilerplate#790]
Hello, you would have an example of the parameters that we should put in the apple sign in environment, right in this line https://github.com/brocoders/nestjs-boilerplate/blob/b21ac9d5812d2cc10b53103d2a519401ce2c8eeb/env-example#L51

Could you indicate if you have where to get the parameters, could you extend the env.example with an example array?

Thanks good job in template

**Comment by Shchepotin** [comment]
@oularrea sorry for long answer.

Example:
```txt
APPLE_APP_AUDIENCE=["com.company", "com.company.webapp"]
```

More info here: https://www.npmjs.com/package/apple-signin-auth

<img width="755" alt="image" src="https://user-images.githubusercontent.com/6001723/205364243-d1472623-98cd-4908-954e-e24310a8791c.png">

**Comment by Shchepotin** [comment]
@oularrea also, please read this comment: https://github.com/brocoders/nestjs-boilerplate/issues/641#issuecomment-1126897384
