### ISSUE TITLE
Unable to connect to the database on Production

### ISSUE THREAD

**Issue by Dhaxor** [brocoders/nestjs-boilerplate#875]
I deployed my app to railway app but I am getting this error. I've changed the node_Env to production also I have my PORT as 3000 but the error is still persisting. Below is a screenshot of the error
![typeorm error](https://user-images.githubusercontent.com/46064597/219966337-0d885633-ceb7-4927-9816-06a4977b0a59.jpg)

**Comment by Shchepotin** [comment]
Your app can't connect to database. Please be sure you set correct DATABASE_URL in .env file.

**Comment by Dhaxor** [comment]
> Your app can't connect to database. Please be sure you set correct DATABASE_URL in .env file.

Yea. That was the issue. Thanks
