### ISSUE TITLE
Deployment crashed

### ISSUE THREAD

**Issue by Dhaxor** [brocoders/nestjs-boilerplate#877]
I just deployed my app to railway.app. I have set up the database and added the DATABASE_URL to my env variable but I am getting this error
![waitforit](https://user-images.githubusercontent.com/46064597/220162009-d880f6ee-ed02-469e-b192-8a9b94938aa3.jpg)

**Comment by Shchepotin** [comment]
@Dhaxor if you store env variables in railway, please remove all variables in `.env` (but do not remove .env file). I mean this file must be empty.

**Comment by Dhaxor** [comment]
@Shchepotin I am not sure I understand you correctly. Currently I don't have `.env` pushed to github. for railway, I copied my `.env` secrets to railway variables. Are you saying I should push the `.env` to github ?

**Comment by Shchepotin** [comment]
> Are you saying I should push the .env to github ?
No, I mean when you deploy your project to railway please create empty `.env` file, like: `echo '' > .env`

**Comment by Dhaxor** [comment]
> > Are you saying I should push the .env to github ?
> > No, I mean when you deploy your project to railway please create empty `.env` file, like: `echo '' > .env`

I just tried this now and still the same error.

**Comment by Shchepotin** [comment]
Your problem is that app can't connect to database, please deep dive in your configurations.

Also I see you try connect to host `postgres`, I not sure this correct in your case, looks like app pickup config from default `env-example` file

**Comment by okanisildar** [comment]
I'm having a similar issue here. I deployed the boilerplate to fly.io and having the following error;

> nc: bad address 'postgres'

I tried to empty .env file but it did not help. I don't know how it finds "postgres". I have the DATABASE_URL as secret so it should check only that. Do you have any other idea what could be the problem? @Shchepotin
