### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Yassin-H-Rassul** [brocoders/nestjs-boilerplate#929]
Sorry for my noob questioning, but is there any doc or help on how to deploy the containers on server and set up ci/cd?
Thanks in advance.

**Comment by Shchepotin** [comment]
@Yassin-H-Rassul there are many options for deployment: Heroku, AWS, Fly.io, your own servers, etc, and CD need configure depending on your requirement. We planing make documentation for deploy on AWS.

What you can do now: Search something like this: "How to deploy NestJS app to AWS" or "How to deploy NestJS app to Heroku".

**Comment by Yassin-H-Rassul** [comment]
> @Yassin-H-Rassul there are many options for deployment: Heroku, AWS, Fly.io, your own servers, etc, and CD need configure depending on your requirement. We planing make documentation for deploy on AWS.
> 
> What you can do now: Search something like this: "How to deploy NestJS app to AWS" or "How to deploy NestJS app to Heroku".

Thanks so much bro, appreciate it
