### ISSUE TITLE
bug in Confirm mail

### ISSUE THREAD

**Issue by adixoncode** [brocoders/nestjs-boilerplate#938]
Always when i send to http://localhost:3000/api/v1/auth/email/register
i get: {"statusCode":404,"message":"Cannot GET /confirm-email/0ace23e1ad6fde095f933e65b8ff2b461c122197e9f6321b04690ae99fc0315d","error":"Not Found"}

why? I must add some specific settings?

**Comment by jkoutavas** [comment]
@adixoncode I have the same problem.

**Comment by Shchepotin** [comment]
@jkoutavas it should be a path to your frontend app, not the backend server.

example: https://my-frontend-app.com/confirm-email/0ace23e1ad6fde095f933e65b8ff2b461c122197e9f6321b04690ae99fc0315d
